[2024-02-25 08:01:02.775] [debug] 24/02/25 08:01:02.774 DEBUG  loader(316).module_job(217).main(50) [Platform/OS] Windows (win)
[2024-02-25 08:01:02.778] [debug] 24/02/25 08:01:02.778 DEBUG  loader(316).module_job(217).main(51) [Build Level] 0
[2024-02-25 08:01:02.779] [debug] 24/02/25 08:01:02.779 DEBUG  loader(316).module_job(217).main(52) [Execution Mode] development
[2024-02-25 08:01:02.780] [debug] 24/02/25 08:01:02.780 DEBUG  loader(316).module_job(217).main(53) [Production Mode] false
[2024-02-25 08:01:02.781] [debug] 24/02/25 08:01:02.781 DEBUG  loader(316).module_job(217).main(54) [Build Mode] false
[2024-02-25 08:01:02.782] [debug] 24/02/25 08:01:02.782 DEBUG  loader(316).module_job(217).main(55) [AppData Path] D:\desktop\Core\Projects\team.gg\team-gg
[2024-02-25 08:01:02.783] [debug] 24/02/25 08:01:02.783 DEBUG  loader(316).module_job(217).main(56) [UserData Path] D:\desktop\Core\
[2024-02-25 08:01:06.379] [error] 24/02/25 08:01:06.378 ERROR  node:events(514).main(81)            [Trace: events:514(514).main(75).serviceGroup(34).windowConfig(25)] Failed to load image from path 'D:\desktop\Core\Projects\team.gg\team-gg\public\tray\tray.png'
[2024-02-25 08:01:06.447] [error] 24/02/25 08:01:06.446 ERROR  node:events(514).warning(123).&(60)  (node:9748) UnhandledPromiseRejectionWarning: Error: Failed to load image from path 'D:\desktop\Core\Projects\team.gg\team-gg\public\tray\tray.png'
    at default (file:///D:/desktop/Core/Projects/team.gg/team-gg/public/electron/configures/window.config.js:25:12)
    at ServiceGroup.configureAndRun (file:///D:/desktop/Core/Projects/team.gg/team-gg/public/electron/core/serviceGroup.js:34:5)
    at App.<anonymous> (file:///D:/desktop/Core/Projects/team.gg/team-gg/public/electron/core/main.js:75:18)
    at App.emit (node:events:514:28)
(Use `electron --trace-warnings ...` to show where the warning was created)
[2024-02-25 08:01:06.454] [error] 24/02/25 08:01:06.453 ERROR  node:events(514).warning(123).&(60)  (node:9748) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
