[2024-02-25 08:00:39.979] [debug] 24/02/25 08:00:39.972 DEBUG  loader(316).module_job(217).main(50) [Platform/OS] Windows (win)
[2024-02-25 08:00:39.983] [debug] 24/02/25 08:00:39.982 DEBUG  loader(316).module_job(217).main(51) [Build Level] 0
[2024-02-25 08:00:39.984] [debug] 24/02/25 08:00:39.984 DEBUG  loader(316).module_job(217).main(52) [Execution Mode] development
[2024-02-25 08:00:39.985] [debug] 24/02/25 08:00:39.985 DEBUG  loader(316).module_job(217).main(53) [Production Mode] false
[2024-02-25 08:00:39.986] [debug] 24/02/25 08:00:39.986 DEBUG  loader(316).module_job(217).main(54) [Build Mode] false
[2024-02-25 08:00:39.986] [debug] 24/02/25 08:00:39.986 DEBUG  loader(316).module_job(217).main(55) [AppData Path] D:\desktop\Core\Projects\team.gg\team-gg
[2024-02-25 08:00:39.987] [debug] 24/02/25 08:00:39.987 DEBUG  loader(316).module_job(217).main(56) [UserData Path] D:\desktop\Core\
[2024-02-25 08:00:40.096] [error] 24/02/25 08:00:40.095 ERROR  node:events(514).main(81)            [Trace: events:514(514).main(75).serviceGroup(34).windowConfig(12)] __dirname is not defined
[2024-02-25 08:00:40.098] [error] 24/02/25 08:00:40.097 ERROR  node:events(514).warning(123).&(60)  (node:22784) UnhandledPromiseRejectionWarning: ReferenceError: __dirname is not defined
    at default (file:///D:/desktop/Core/Projects/team.gg/team-gg/public/electron/configures/window.config.js:12:26)
    at ServiceGroup.configureAndRun (file:///D:/desktop/Core/Projects/team.gg/team-gg/public/electron/core/serviceGroup.js:34:5)
    at App.<anonymous> (file:///D:/desktop/Core/Projects/team.gg/team-gg/public/electron/core/main.js:75:18)
    at App.emit (node:events:514:28)
(Use `electron --trace-warnings ...` to show where the warning was created)
[2024-02-25 08:00:40.099] [error] 24/02/25 08:00:40.099 ERROR  node:events(514).warning(123).&(60)  (node:22784) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
